<?php
/**
 * Value object representing a blog post generated by an AI provider.
 *
 * @package ChangelogToBlogPost\AI
 */

namespace TenUp\ChangelogToBlogPost\AI;

/**
 * Immutable output of a successful AI generation call.
 */
readonly class GeneratedPost {

	/**
	 * Constructor.
	 *
	 * @param string $title         Generated post title.
	 * @param string $content       Generated post body (HTML).
	 * @param string $provider_slug Provider slug that produced this post (e.g. 'openai').
	 */
	public function __construct(
		public string $title,
		public string $content,
		public string $provider_slug,
	) {}

	/**
	 * Parses a raw AI response into a GeneratedPost.
	 *
	 * Expected format: line 1 = subtitle, blank line, then HTML body.
	 * Falls back to a generic title if the subtitle line is empty.
	 *
	 * @param string      $raw           Raw text response from the AI provider.
	 * @param ReleaseData $data          Source release data (for fallback title).
	 * @param string      $provider_slug Provider slug.
	 * @return self
	 */
	public static function from_raw_text( string $raw, ReleaseData $data, string $provider_slug ): self {
		$raw   = trim( $raw );
		$parts = explode( "\n", $raw, 2 );
		$title = trim( $parts[0] ?? '' );
		$body  = trim( $parts[1] ?? '' );

		if ( '' === $title ) {
			$title = sprintf(
				/* translators: 1: repo identifier, 2: release tag */
				__( '%1$s %2$s Release Notes', 'changelog-to-blog-post' ),
				$data->identifier,
				$data->tag
			);
		}

		return new self(
			title:         $title,
			content:       $body,
			provider_slug: $provider_slug,
		);
	}
}
