<?php
/**
 * Value object representing a blog post generated by an AI provider.
 *
 * @package GitHubReleasePosts\AI
 */

namespace GitHubReleasePosts\AI;

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Immutable output of a successful AI generation call.
 */
readonly class GeneratedPost {

	/**
	 * Constructor.
	 *
	 * @param string $title          Generated post subtitle.
	 * @param string $content        Generated post body (HTML).
	 * @param string $provider_slug  Provider slug that produced this post (e.g. 'openai').
	 * @param string $slug_keywords  Hyphenated slug keywords (e.g. 'ai-usage-tracking-security').
	 * @param string $excerpt        Post excerpt / meta description (150-160 chars).
	 */
	public function __construct(
		public string $title,
		public string $content,
		public string $provider_slug,
		public string $slug_keywords = '',
		public string $excerpt = '',
	) {}

	/**
	 * Parses a raw AI response into a GeneratedPost.
	 *
	 * Expected format:
	 *   Line 1: subtitle
	 *   Line 2: slug keywords
	 *   Line 3: excerpt
	 *   Line 4: blank
	 *   Line 5+: HTML body
	 *
	 * Models don't always honor the spacing contract, so the two metadata
	 * lines are read as the next two non-blank lines after the title rather
	 * than fixed positions. (Observed in production: a blank line after the
	 * title shifted the keywords into the excerpt seat and leaked the real
	 * excerpt into the post body.) Falls back gracefully if slug/excerpt
	 * lines are missing.
	 *
	 * @param string      $raw           Raw text response from the AI provider.
	 * @param ReleaseData $data          Source release data (for fallback title).
	 * @param string      $provider_slug Provider slug.
	 * @return self
	 */
	public static function from_raw_text( string $raw, ReleaseData $data, string $provider_slug ): self {
		$raw   = trim( $raw );
		$lines = explode( "\n", $raw );

		// Line 1 is the title by contract; strip any tags and cap the length so a
		// model that emits HTML or body content here can't produce a markup title
		// or a runaway one. An all-markup line collapses to '' and hits the
		// fallback title below.
		$title = trim( wp_strip_all_tags( trim( $lines[0] ?? '' ) ) );
		if ( mb_strlen( $title ) > 200 ) {
			$title = trim( mb_substr( $title, 0, 200 ) );
		}
		// Consume the next two non-blank lines as slug keywords and excerpt,
		// tolerating blank lines the model may insert between them.
		$cursor = 1;
		while ( isset( $lines[ $cursor ] ) && '' === trim( $lines[ $cursor ] ) ) {
			++$cursor;
		}
		$keywords_index = $cursor;
		$slug_keywords  = trim( $lines[ $cursor ] ?? '' );
		++$cursor;
		while ( isset( $lines[ $cursor ] ) && '' === trim( $lines[ $cursor ] ) ) {
			++$cursor;
		}
		$excerpt = trim( $lines[ $cursor ] ?? '' );
		++$cursor;

		// Find the body — skip blank lines after the metadata lines.
		$body_start = $cursor;
		while ( isset( $lines[ $body_start ] ) && '' === trim( $lines[ $body_start ] ) ) {
			++$body_start;
		}
		$body = trim( implode( "\n", array_slice( $lines, $body_start ) ) );

		// Validate slug keywords — should be lowercase hyphenated words, no HTML.
		if ( preg_match( '/</', $slug_keywords ) || strlen( $slug_keywords ) > 80 ) {
			// AI returned HTML or something too long — likely body content shifted up.
			// Fall back: treat everything after the title as body.
			$body          = trim( implode( "\n", array_slice( $lines, $keywords_index ) ) );
			$slug_keywords = '';
			$excerpt       = '';
		}

		// Validate excerpt — should be plain text, not HTML tags.
		if ( preg_match( '/^<[a-z]/', $excerpt ) ) {
			// Excerpt looks like HTML body — shift down.
			$body    = trim( $excerpt . "\n" . $body );
			$excerpt = '';
		}

		// A slug-shaped excerpt is keywords in the wrong seat (e.g. the model
		// swapped the metadata lines) — never save it as a visible excerpt.
		if ( '' !== $excerpt && preg_match( '/^[a-z0-9]+(?:-[a-z0-9]+)+$/', $excerpt ) ) {
			if ( '' === $slug_keywords ) {
				$slug_keywords = $excerpt;
			}
			$excerpt = '';
		}

		if ( '' === $title ) {
			$title = sprintf(
				/* translators: 1: repo identifier, 2: release tag */
				__( '%1$s %2$s Release Notes', 'auto-release-posts-for-github' ),
				$data->identifier,
				$data->tag
			);
		}

		return new self(
			title:         $title,
			content:       $body,
			provider_slug: $provider_slug,
			slug_keywords: $slug_keywords,
			excerpt:       $excerpt,
		);
	}
}
